const GET_LISTS = 'GET_LISTS';
const CREATE_LIST = 'CREATE_LIST';
const LIST_EDIT = 'LIST_EDIT';
const LIST_SUBMIT = 'LIST_SUBMIT';
const LIST_DELETE = 'LIST_DELETE';

export { GET_LISTS, CREATE_LIST, LIST_EDIT, LIST_SUBMIT, LIST_DELETE };
