const GET_TODOS = 'GET_TODOS';
const TODO_EDIT = 'TODO_EDIT';
const TODO_SUBMIT = 'TODO_SUBMIT';
const TODO_CREATE = 'TODO_CREATE';
const TODO_DONE = 'TODO_DONE';
const TODO_DELETE = 'TODO_DELETE';

export { GET_TODOS, TODO_EDIT, TODO_SUBMIT, TODO_CREATE, TODO_DONE, TODO_DELETE }
