const GET_USER = 'GET_USER';
const USER_CHANGE_USERNAME = 'USER_CHANGE_USERNAME';
const USER_SUBMIT_USERNAME = 'USER_SUBMIT_USERNAME';
const USER_DELETE = 'USER_DELETE';


export { GET_USER, USER_CHANGE_USERNAME, USER_SUBMIT_USERNAME, USER_DELETE }
